name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build:production
      - run: zip -r function.zip . --exclude @.funcignore --exclude .funcignore
      - uses: actions/upload-artifact@v2
        with:
          name: function-zip-zip.zip
          path: function.zip
          retention-days: 1
      - run: echo "🍏 This job's status is ${{ job.status }}."
